### ISSUE TITLE
Crash when displaying mercenary inventory

### ISSUE THREAD

**Issue by damienfayet** [cyhyraethz/d2r-basic-qol#10]
Hello,

The game crashes whenever I try to open my mercenary inventory. When pressing O instant crash, with old chars and same with a new char created after patch.

Any idea ?

Thanks !

**Comment by damienfayet** [comment]
Tried to install D2R_Expanded_NoMerc_3.3 but didn't change anything.

**Comment by cyhyraethz** [comment]
Are you using the most recent version of the mod (Basic QoL v2.0)? It was updated for patch 2.4 and older versions won't work properly. It also includes an updated version of the expanded inventory mod in the `optional` folder.

I recommend deleting the `basic-qol.mpq` folder from your `Diablo II Resurrected\mods\basic-qol` directory and replacing it with the updated version, and following [the instructions in the README](https://github.com/cyhyraethz/d2r-basic-qol#how-to-add-features) to add the expanded inventory mod to the new version of Basic QoL.

**Comment by xScarbo** [comment]
Similar issue here. Mine crashes too few seconds after opening Merc inventory

**Comment by xScarbo** [comment]
Version 2.0 by the way, just found out about this great mod today

**Comment by damienfayet** [comment]
Hello,

Thanks, I resolved it deleting everything and installing it again.

Be careful, to either save you Saved chars before operation or be sure to add extended storage BEFORE launching the game, if not you will lose all objects in the "extended part" of your different inventories/stash.

Thanks for the help
