### ISSUE TITLE
A Few Suggestions

### ISSUE THREAD

**Issue by xScarbo** [cyhyraethz/d2r-basic-qol#12]
First of all, thank you so much for making this QoL mod. It has doubled my enjoyment of this game. I have a few ideas that'd make it even better. 

First, I'd love to have the option to extend couple more columns of the belt slots.
That'd allow players to slot in Antidote and Thaw potions without excluding hp/mana potions.
In addition to the expansion, it'd be nice if one can customize where each potion automatically goes (for example, hp pot for 1st column, mp pot for 2nd etc).

Second, I'd love to have a search capability [ctrl +f]  for both the character screen  and stash.
That'd make it a lot easier to look for a specific character (especially if you have like 50 like me) and find certain items.

I know very little about modding, so I don't know if adding these features is even possible in the first place.
But I think lots of people will find these additions super helpful. Thanks.

**Comment by cyhyraethz** [comment]
Thank you for the suggestions, and I'm glad you are enjoying the mod.

Those do seem like they would be nice quality of life improvements.

Unfortunately, I have no idea how to implement them, and I suspect it may not even be possible.
