### ISSUE TITLE
Opening the Skill Tree as a Barbarian Crashes the Game

### ISSUE THREAD

**Issue by xScarbo** [cyhyraethz/d2r-basic-qol#13]
Did some experimenting and found out this only happens for Barbarian characters, no matter the difficulty or location. 
So basically as of now, mod is unusable on Barbarian characters.

**Comment by pierremac** [comment]
I didn't test extensively. But I just tried with my (berserker) barb in Hell and opening the skill tree does not crash my game...

**Comment by xScarbo** [comment]
> I didn't test extensively. But I just tried with my (berserker) barb in Hell and opening the skill tree does not crash my game...

Do you have the current mod version/game patch?
Also, could you try testing with Normal/Nightmare? I haven't unlocked Hell in my Barb.

**Comment by pierremac** [comment]
Yes, I have the mod v2.0 and the game v1.2.68992.
I just tried in normal and nightmare and both seem to function normally.
Definitely no crash when I open the skill tree.
It's a long shot but did you try to respec?

**Comment by xScarbo** [comment]
Not with my Barbarian characters, no. 
But I did respec a bunch on my necromancer and had no issues with it.

**Comment by pierremac** [comment]
I meant you could maybe try to respec your barbarian and see if that fixes it.
But I have no idea, really...

**Comment by cyhyraethz** [comment]
I am unable to replicate the issue with either my existing barbarian or by creating a new barbarian.

**Comment by xScarbo** [comment]
Weird... I tried deleting the mod and reinstalling it. Issue persists.
I tried it without the mod applied and it works normally.

**Comment by xScarbo** [comment]
Is the mod designed for another English unicode, like British en-gb?

**Comment by xScarbo** [comment]
Oh my bad, my base game was not patched yet, that's why lol
