### ISSUE TITLE
Game crashes if you open merc inventory on the new 2.4 PTR Patch

### ISSUE THREAD

**Issue by Glaimbyy** [cyhyraethz/d2r-basic-qol#9]
So I'm having this issue where the Game crashes as soon as I press 'O' to open the Mercs Inventory on the newest PTR Patch while using this Mod. Any Idea why that happens or how I could fix it?

Edit: Seems to have something to do with the weapon. If I open this Char without mod and opn the Mercs inventory it works but the weapon slot is empty (used to be a Reaper's Toll)

Edit2: It's the Mercs Inventory in General, i tried hiring new mercs from all acts and they all crash my game when I open the Merc inventory.

Edit3: Managed to get it to work with the help of cyhyraethz and reinstalling the mod and copying a [different version of the extended mod ](https://www.nexusmods.com/diablo2resurrected/mods/13?tab=files&file_id=1004) into it. This turns off the Merc Inventory though but atleast u can use the merc again.

**Comment by pierremac** [comment]
Can you give a bit more details about the procedure?
How do you "reinstall", do you delete the mod files first?

Also, I have the same crashing issue when I open the merc inventory.
But some characters instantly crash d2r when I try to start a game. I don't even see the loading screen...

**Comment by pierremac** [comment]
Everything seems to be fixed with the new release for 2.4.
Thanks a lot @cyhyraethz !
